#!/bin/bash
# ============================================================================
# System Hardening Module
# ============================================================================
# Functions for kernel hardening, sysctl, and system security
# ============================================================================

configure_sysctl_hardening() {
    log_section "Kernel Hardening (sysctl)"
    
    if [[ "$CONFIGURE_SYSCTL" != "true" ]]; then
        log_info "Sysctl hardening disabled"
        return 0
    fi
    
    local sysctl_conf="/etc/sysctl.d/99-hardening.conf"
    
    log_info "Applying kernel hardening parameters"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create $sysctl_conf with hardening parameters"
        return 0
    fi
    
    # Create hardening configuration
    cat > "$sysctl_conf" <<EOF
# Kernel Hardening Configuration
# Generated by linux-base-setup on $(date)

# IP Forwarding
net.ipv4.ip_forward = $([ "$SYSCTL_IP_FORWARDING" == "true" ] && echo "1" || echo "0")
net.ipv6.conf.all.forwarding = $([ "$SYSCTL_IP_FORWARDING" == "true" ] && echo "1" || echo "0")

# Source routing
net.ipv4.conf.all.accept_source_route = $([ "$SYSCTL_ACCEPT_SOURCE_ROUTE" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.accept_source_route = $([ "$SYSCTL_ACCEPT_SOURCE_ROUTE" == "true" ] && echo "1" || echo "0")
net.ipv6.conf.all.accept_source_route = $([ "$SYSCTL_ACCEPT_SOURCE_ROUTE" == "true" ] && echo "1" || echo "0")
net.ipv6.conf.default.accept_source_route = $([ "$SYSCTL_ACCEPT_SOURCE_ROUTE" == "true" ] && echo "1" || echo "0")

# ICMP redirects
net.ipv4.conf.all.accept_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.accept_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv6.conf.all.accept_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv6.conf.default.accept_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.all.secure_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.secure_redirects = $([ "$SYSCTL_ACCEPT_REDIRECTS" == "true" ] && echo "1" || echo "0")

# Send redirects
net.ipv4.conf.all.send_redirects = $([ "$SYSCTL_SEND_REDIRECTS" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.send_redirects = $([ "$SYSCTL_SEND_REDIRECTS" == "true" ] && echo "1" || echo "0")

# Reverse path filtering (anti-spoofing)
net.ipv4.conf.all.rp_filter = $([ "$SYSCTL_RP_FILTER" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.rp_filter = $([ "$SYSCTL_RP_FILTER" == "true" ] && echo "1" || echo "0")

# Log Martians (packets with impossible addresses)
net.ipv4.conf.all.log_martians = $([ "$SYSCTL_LOG_MARTIANS" == "true" ] && echo "1" || echo "0")
net.ipv4.conf.default.log_martians = $([ "$SYSCTL_LOG_MARTIANS" == "true" ] && echo "1" || echo "0")

# SYN flood protection
net.ipv4.tcp_syncookies = $([ "$SYSCTL_TCP_SYNCOOKIES" == "true" ] && echo "1" || echo "0")
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# ICMP broadcast/multicast
net.ipv4.icmp_echo_ignore_broadcasts = $([ "$SYSCTL_ICMP_ECHO_IGNORE_BROADCASTS" == "true" ] && echo "1" || echo "0")
net.ipv4.icmp_ignore_bogus_error_responses = $([ "$SYSCTL_ICMP_IGNORE_BOGUS_ERROR_RESPONSES" == "true" ] && echo "1" || echo "0")

# Kernel hardening
kernel.dmesg_restrict = $([ "$SYSCTL_KERNEL_DMESG_RESTRICT" == "true" ] && echo "1" || echo "0")
kernel.kptr_restrict = $([ "$SYSCTL_KERNEL_KPTR_RESTRICT" == "true" ] && echo "1" || echo "0")
kernel.randomize_va_space = $([ "$SYSCTL_RANDOMIZE_VA_SPACE" == "true" ] && echo "2" || echo "0")
kernel.yama.ptrace_scope = 1
kernel.panic = 10
kernel.panic_on_oops = 1

# Core dump restrictions
fs.suid_dumpable = 0

# Memory protection
kernel.exec-shield = 1
kernel.kexec_load_disabled = 1

# Network performance tuning
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.rmem_default = 67108864
net.core.wmem_default = 67108864
net.core.netdev_max_backlog = 5000
net.core.somaxconn = 4096

# IPv6 hardening (if not using IPv6)
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# Filesystem protections
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2
EOF
    
    # Apply sysctl settings
    log_info "Applying sysctl settings"
    if sysctl -p "$sysctl_conf" >> "$LOG_FILE" 2>&1; then
        log_success "Sysctl hardening applied"
    else
        log_error "Failed to apply some sysctl settings"
        return 1
    fi
    
    return 0
}

disable_uncommon_protocols() {
    log_section "Disabling Uncommon Network Protocols"
    
    if [[ "$DISABLE_UNCOMMON_PROTOCOLS" != "true" ]]; then
        log_info "Protocol disabling skipped"
        return 0
    fi
    
    local modprobe_conf="/etc/modprobe.d/uncommon-protocols.conf"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would disable uncommon protocols"
        return 0
    fi
    
    log_info "Disabling uncommon network protocols"
    
    cat > "$modprobe_conf" <<EOF
# Disable uncommon network protocols
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
EOF
    
    log_success "Uncommon protocols disabled"
    return 0
}

disable_usb_storage() {
    log_section "USB Storage Configuration"
    
    if [[ "$DISABLE_USB_STORAGE" != "true" ]]; then
        log_info "USB storage remains enabled"
        return 0
    fi
    
    local modprobe_conf="/etc/modprobe.d/disable-usb-storage.conf"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would disable USB storage"
        return 0
    fi
    
    log_info "Disabling USB storage"
    
    echo "install usb-storage /bin/true" > "$modprobe_conf"
    
    # Unload module if loaded
    if lsmod | grep -q usb_storage; then
        rmmod usb_storage 2>/dev/null || true
    fi
    
    log_success "USB storage disabled"
    return 0
}

configure_apparmor() {
    log_section "AppArmor Configuration"
    
    if [[ "$CONFIGURE_APPARMOR" != "true" ]]; then
        log_info "AppArmor configuration disabled"
        return 0
    fi
    
    log_info "Configuring AppArmor"
    
    # Install AppArmor utilities
    install_package "apparmor"
    install_package "apparmor-utils"
    install_package "apparmor-profiles"
    install_package "apparmor-profiles-extra"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would enable AppArmor"
        return 0
    fi
    
    # Enable AppArmor
    systemctl enable apparmor >> "$LOG_FILE" 2>&1
    systemctl start apparmor >> "$LOG_FILE" 2>&1
    
    # Set profiles to enforce mode
    aa-enforce /etc/apparmor.d/* 2>/dev/null || true
    
    # Display status
    log_success "AppArmor configured and enabled"
    aa-status | head -20 | tee -a "$LOG_FILE"
    
    return 0
}

configure_shared_memory() {
    log_section "Shared Memory Security"
    
    local fstab="/etc/fstab"
    local shm_mount="tmpfs /run/shm tmpfs defaults,noexec,nosuid,nodev 0 0"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would secure /run/shm"
        return 0
    fi
    
    backup_file "$fstab"
    
    if ! grep -q "/run/shm" "$fstab"; then
        echo "$shm_mount" >> "$fstab"
        log_info "Added secure shared memory mount to fstab"
        
        # Remount
        mount -o remount /run/shm 2>/dev/null || true
        log_success "Shared memory secured"
    else
        log_info "Shared memory already configured"
    fi
    
    return 0
}

configure_coredumps() {
    log_section "Core Dump Restrictions"
    
    local limits_conf="/etc/security/limits.d/10-coredump.conf"
    local sysctl_conf="/etc/sysctl.d/50-coredump.conf"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would disable core dumps"
        return 0
    fi
    
    log_info "Disabling core dumps"
    
    # Disable via limits
    cat > "$limits_conf" <<EOF
# Disable core dumps
* hard core 0
* soft core 0
EOF
    
    # Disable via sysctl
    cat > "$sysctl_conf" <<EOF
# Disable core dumps
kernel.core_pattern=|/bin/false
fs.suid_dumpable = 0
EOF
    
    sysctl -p "$sysctl_conf" >> "$LOG_FILE" 2>&1
    
    # Disable via systemd
    mkdir -p /etc/systemd/coredump.conf.d
    cat > /etc/systemd/coredump.conf.d/disable.conf <<EOF
[Coredump]
Storage=none
ProcessSizeMax=0
EOF
    
    systemctl daemon-reload
    
    log_success "Core dumps disabled"
    return 0
}

configure_kernel_modules() {
    log_section "Kernel Module Security"
    
    local modprobe_conf="/etc/modprobe.d/security.conf"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure kernel module security"
        return 0
    fi
    
    log_info "Configuring kernel module security"
    
    cat > "$modprobe_conf" <<EOF
# Disable uncommon filesystems
install cramfs /bin/true
install freevxfs /bin/true
install jffs2 /bin/true
install hfs /bin/true
install hfsplus /bin/true
install udf /bin/true

# Disable uncommon network protocols
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true

# Disable bluetooth if not needed
#install bluetooth /bin/true
EOF
    
    log_success "Kernel module security configured"
    return 0
}
