#!/bin/bash
# ============================================================================
# Security Tools Module
# ============================================================================
# Functions for installing and configuring security tools
# ============================================================================

configure_fail2ban() {
    log_section "Fail2Ban Configuration"
    
    if [[ "$INSTALL_FAIL2BAN" != "true" ]]; then
        log_info "Fail2Ban installation disabled"
        return 0
    fi
    
    log_info "Installing and configuring Fail2Ban"
    
    # Install fail2ban
    install_package "fail2ban"
    
    local jail_local="/etc/fail2ban/jail.local"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure Fail2Ban"
        return 0
    fi

    # Only backup if file already exists
    [[ -f "$jail_local" ]] && backup_file "$jail_local"
    
    # Determine backend based on system configuration
    local f2b_backend="auto"

    # On systemd systems without /var/log/auth.log, use systemd backend
    if [[ -d /run/systemd/system ]] && [[ ! -f /var/log/auth.log ]]; then
        f2b_backend="systemd"
        log_info "Using systemd backend for Fail2Ban (no auth.log found)"
    fi

    # Create jail.local configuration
    cat > "$jail_local" <<EOF
# Fail2Ban configuration
# Generated by linux-base-setup on $(date)

[DEFAULT]
# Ban settings
bantime = $FAIL2BAN_BAN_TIME
findtime = $FAIL2BAN_FIND_TIME
maxretry = $FAIL2BAN_MAX_RETRY

# Action - use basic action (ban only, no mail)
action = %(action_)s

# Ignore local connections
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = $SSH_PORT
backend = $f2b_backend
maxretry = $FAIL2BAN_MAX_RETRY
bantime = $FAIL2BAN_BAN_TIME
EOF

    # Verify configuration is valid
    log_info "Verifying Fail2Ban configuration"
    if ! fail2ban-client -t >> "$LOG_FILE" 2>&1; then
        log_error "Fail2Ban configuration test failed. Check $LOG_FILE for details"
        log_warning "Fail2Ban will need manual configuration"
        return 1
    fi

    # Enable and start fail2ban
    enable_service "fail2ban"
    if ! restart_service "fail2ban"; then
        log_warning "Fail2Ban service restart had issues"
    fi

    # Display status (wait a bit longer for service to fully start)
    sleep 5
    if fail2ban-client status >> "$LOG_FILE" 2>&1; then
        log_success "Fail2Ban configured and running"
        fail2ban-client status sshd >> "$LOG_FILE" 2>&1 || true
    else
        log_warning "Fail2Ban service may need manual verification. Check: systemctl status fail2ban"
    fi

    return 0
}

configure_auditd() {
    log_section "Auditd Configuration"
    
    if [[ "$INSTALL_AUDITD" != "true" ]]; then
        log_info "Auditd installation disabled"
        return 0
    fi
    
    log_info "Installing and configuring Auditd"
    
    # Install auditd
    install_package "auditd"
    install_package "audispd-plugins"
    
    if [[ "$CONFIGURE_AUDITD" != "true" ]]; then
        log_info "Auditd configuration disabled"
        return 0
    fi
    
    local audit_rules="/etc/audit/rules.d/hardening.rules"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure Auditd rules"
        return 0
    fi

    # Only backup if file already exists
    [[ -f "$audit_rules" ]] && backup_file "$audit_rules"
    
    # Create audit rules
    cat > "$audit_rules" <<'EOF'
# Audit Rules for System Hardening
# Generated by linux-base-setup

# Remove any existing rules
-D

# Buffer Size
-b 8192

# Failure Mode (0=silent 1=printk 2=panic)
-f 1

# Audit system calls
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
-a always,exit -F arch=b32 -S clock_settime -k time-change

# Monitor user/group changes
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# Monitor sudo configuration
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# Monitor SSH configuration
-w /etc/ssh/sshd_config -p wa -k sshd_config

# Monitor hostname changes
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale
-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale
-w /etc/issue -p wa -k system-locale
-w /etc/issue.net -p wa -k system-locale
-w /etc/hosts -p wa -k system-locale
-w /etc/hostname -p wa -k system-locale
-w /etc/network -p wa -k system-locale

# Monitor kernel module loading/unloading
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules

# Monitor privileged commands
-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd
-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-sudo
-a always,exit -F path=/usr/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-su
-a always,exit -F path=/usr/sbin/usermod -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-usermod
-a always,exit -F path=/usr/sbin/useradd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-useradd
-a always,exit -F path=/usr/sbin/userdel -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-userdel
-a always,exit -F path=/usr/sbin/groupadd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-groupadd
-a always,exit -F path=/usr/sbin/groupmod -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-groupmod
-a always,exit -F path=/usr/sbin/groupdel -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-groupdel

# Monitor file permission changes
-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod

# Monitor unauthorized file access attempts
-a always,exit -F arch=b64 -S open -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b64 -S open -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S open -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access

# Monitor file deletions
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete
-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete

# Monitor login/logout events
-w /var/log/lastlog -p wa -k logins
-w /var/run/faillock/ -p wa -k logins

# Monitor session initiation
-w /var/run/utmp -p wa -k session
-w /var/log/wtmp -p wa -k logins
-w /var/log/btmp -p wa -k logins

# Make configuration immutable (must be last)
-e 2
EOF
    
    # Restart auditd
    log_info "Restarting auditd service"
    service auditd restart >> "$LOG_FILE" 2>&1 || systemctl restart auditd >> "$LOG_FILE" 2>&1
    
    log_success "Auditd configured with comprehensive rules"
    
    return 0
}

install_rkhunter() {
    log_section "RKHunter Installation"
    
    if [[ "$INSTALL_RKHUNTER" != "true" ]]; then
        log_info "RKHunter installation disabled"
        return 0
    fi
    
    log_info "Installing RKHunter (Rootkit Hunter)"
    
    install_package "rkhunter"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure RKHunter"
        return 0
    fi
    
    # Update rkhunter database (non-fatal if update fails)
    log_info "Updating RKHunter database"
    if rkhunter --update >> "$LOG_FILE" 2>&1; then
        log_success "RKHunter database updated"
    else
        log_warning "RKHunter database update failed (may be network issue). Run manually: rkhunter --update"
    fi

    # Set baseline (non-fatal if fails)
    log_info "Setting RKHunter baseline"
    if rkhunter --propupd >> "$LOG_FILE" 2>&1; then
        log_success "RKHunter baseline set"
    else
        log_warning "RKHunter baseline failed. Run manually: rkhunter --propupd"
    fi

    # Configure email alerts (if desired)
    local rkhunter_conf="/etc/rkhunter.conf"
    [[ -f "$rkhunter_conf" ]] && backup_file "$rkhunter_conf"

    if [[ -f "$rkhunter_conf" ]]; then
        sed -i 's/^#MAIL-ON-WARNING=.*/MAIL-ON-WARNING=root@localhost/' "$rkhunter_conf"
        sed -i 's/^#MAIL_CMD=.*/MAIL_CMD=mail -s "[rkhunter] Warnings found for ${HOST_NAME}"/' "$rkhunter_conf"
    fi

    log_success "RKHunter installed and configured"
    log_info "Run 'rkhunter --check' to perform manual scans"
    
    return 0
}

install_lynis() {
    log_section "Lynis Installation"
    
    if [[ "$INSTALL_LYNIS" != "true" ]]; then
        log_info "Lynis installation disabled"
        return 0
    fi
    
    log_info "Installing Lynis (Security Auditing Tool)"
    
    install_package "lynis"
    
    log_success "Lynis installed"
    log_info "Run 'lynis audit system' to perform security audit"
    
    return 0
}

configure_aide() {
    log_section "AIDE Configuration (File Integrity)"
    
    if [[ "$INTERACTIVE" != "true" ]]; then
        return 0
    fi
    
    if ! prompt_yes_no "Install AIDE (Advanced Intrusion Detection Environment)?" "n"; then
        log_info "AIDE installation skipped"
        return 0
    fi
    
    log_info "Installing AIDE"
    
    install_package "aide"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would initialize AIDE database"
        return 0
    fi
    
    log_info "Initializing AIDE database (this may take several minutes)"
    aideinit >> "$LOG_FILE" 2>&1 &
    show_progress "Initializing AIDE database" $!
    wait
    
    # Move database
    if [[ -f /var/lib/aide/aide.db.new ]]; then
        mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
        log_success "AIDE database initialized"
        log_info "Run 'aide --check' to verify file integrity"
    else
        log_error "AIDE database initialization failed"
        return 1
    fi
    
    return 0
}
