#!/bin/bash
# ============================================================================
# SSH Hardening Module
# ============================================================================
# Functions for hardening SSH daemon configuration
# ============================================================================

configure_ssh() {
    log_section "SSH Configuration and Hardening"
    
    if [[ "$CONFIGURE_SSH" != "true" ]]; then
        log_info "SSH configuration disabled"
        return 0
    fi
    
    local sshd_config="/etc/ssh/sshd_config"
    
    # Backup original config
    backup_file "$sshd_config"
    
    log_info "Hardening SSH configuration"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would modify SSH configuration:"
        log_info "  Port: $SSH_PORT"
        log_info "  PermitRootLogin: $SSH_PERMIT_ROOT_LOGIN"
        log_info "  PasswordAuthentication: $SSH_PASSWORD_AUTH"
        log_info "  PubkeyAuthentication: $SSH_PUBKEY_AUTH"
        return 0
    fi
    
    # Create new SSH config
    cat > "$sshd_config" <<EOF
# SSH Daemon Configuration - Hardened
# Generated by linux-base-setup on $(date)

# Network
Port $SSH_PORT
AddressFamily inet
ListenAddress 0.0.0.0

# Protocol
Protocol 2

# Host Keys
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Ciphers and keying
KexAlgorithms $SSH_KEY_EXCHANGE_ALGORITHMS
Ciphers $SSH_CIPHERS
MACs $SSH_MACS
HostKeyAlgorithms $SSH_HOST_KEY_ALGORITHMS

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Authentication
LoginGraceTime ${SSH_LOGIN_GRACE_TIME}s
PermitRootLogin $SSH_PERMIT_ROOT_LOGIN
StrictModes yes
MaxAuthTries $SSH_MAX_AUTH_TRIES
MaxSessions 10

PubkeyAuthentication $SSH_PUBKEY_AUTH
AuthorizedKeysFile .ssh/authorized_keys

# Password authentication
PasswordAuthentication $SSH_PASSWORD_AUTH
PermitEmptyPasswords $SSH_PERMIT_EMPTY_PASSWORDS
ChallengeResponseAuthentication no

# Kerberos/GSSAPI
KerberosAuthentication no
GSSAPIAuthentication no

# PAM
UsePAM $SSH_USE_PAM

# Forwarding
AllowAgentForwarding yes
AllowTcpForwarding yes
X11Forwarding $SSH_X11_FORWARDING
PrintMotd no
PrintLastLog $SSH_PRINT_LAST_LOG
TCPKeepAlive yes

# Client alive (prevent timeout)
ClientAliveInterval $SSH_CLIENT_ALIVE_INTERVAL
ClientAliveCountMax $SSH_CLIENT_ALIVE_COUNT_MAX

# Allow/Deny
#AllowUsers $ADMIN_USERNAME
#AllowGroups sudo

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server

# Banner
#Banner /etc/ssh/banner

# Override
AcceptEnv LANG LC_*
EOF
    
    log_success "SSH configuration updated"
    
    # Generate Ed25519 host key if missing
    if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
        log_info "Generating Ed25519 host key"
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" >> "$LOG_FILE" 2>&1
        log_success "Ed25519 host key generated"
    fi
    
    # Test SSH configuration
    log_info "Testing SSH configuration"
    if sshd -t -f "$sshd_config" 2>&1 | tee -a "$LOG_FILE"; then
        log_success "SSH configuration is valid"
    else
        log_error "SSH configuration test failed!"
        log_error "Restoring backup configuration"
        cp "${sshd_config}.$(date +%Y%m%d_%H%M%S)" "$sshd_config"
        return 1
    fi
    
    # Create SSH banner (optional)
    create_ssh_banner
    
    log_success "SSH hardening complete"
    
    # Warning about port change
    if [[ "$SSH_PORT" != "22" ]]; then
        log_warning "============================================"
        log_warning "SSH PORT HAS BEEN CHANGED TO: $SSH_PORT"
        log_warning "============================================"
        log_warning "CRITICAL: Before restarting SSH, ensure:"
        log_warning "1. Firewall allows port $SSH_PORT"
        log_warning "2. You have tested connection from another terminal"
        log_warning "3. You can connect with: ssh -p $SSH_PORT user@host"
        log_warning "============================================"
    fi
    
    return 0
}

create_ssh_banner() {
    local banner_file="/etc/ssh/banner"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create SSH banner"
        return 0
    fi
    
    cat > "$banner_file" <<'EOF'
###############################################################################
#                                                                             #
#                    AUTHORIZED ACCESS ONLY                                   #
#                                                                             #
#  This system is for authorized use only. All activity is monitored and      #
#  logged. Unauthorized access or use may result in disciplinary action       #
#  and/or civil and criminal penalties.                                       #
#                                                                             #
###############################################################################
EOF
    
    # Uncomment Banner line in sshd_config
    sed -i 's|^#Banner /etc/ssh/banner|Banner /etc/ssh/banner|' /etc/ssh/sshd_config
    
    log_info "SSH banner created"
}

restart_ssh_safe() {
    log_section "SSH Service Restart"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would restart SSH service"
        return 0
    fi
    
    if [[ "$INTERACTIVE" == "true" ]]; then
        echo ""
        log_warning "About to restart SSH service"
        log_warning "Ensure you have:"
        log_warning "  1. Configured firewall to allow port $SSH_PORT"
        log_warning "  2. Added your SSH key to $ADMIN_USERNAME"
        log_warning "  3. Tested connection from another terminal"
        echo ""
        
        if ! prompt_yes_no "Have you verified the above and ready to restart SSH?" "n"; then
            log_warning "SSH restart postponed"
            log_info "To restart SSH later, run: systemctl restart sshd"
            return 0
        fi
    fi
    
    log_info "Restarting SSH service"
    
    if systemctl restart sshd >> "$LOG_FILE" 2>&1; then
        log_success "SSH service restarted successfully"
        
        # Verify SSH is running
        sleep 2
        if systemctl is-active --quiet sshd; then
            log_success "SSH service is active and running"
        else
            log_error "SSH service failed to start!"
            log_error "Check: systemctl status sshd"
            log_error "Logs: journalctl -u sshd -n 50"
            return 1
        fi
    else
        log_error "Failed to restart SSH service"
        return 1
    fi
    
    # Display connection info
    local ip_address
    ip_address=$(hostname -I | awk '{print $1}')
    
    echo ""
    log_info "============================================"
    log_info "SSH Configuration Complete"
    log_info "============================================"
    log_info "Connect using:"
    log_info "  ssh -p $SSH_PORT $ADMIN_USERNAME@$ip_address"
    log_info "============================================"
    echo ""
    
    return 0
}

setup_ssh_two_factor() {
    log_section "Two-Factor Authentication Setup (Optional)"
    
    if [[ "$INTERACTIVE" != "true" ]]; then
        log_info "Skipping 2FA setup in non-interactive mode"
        return 0
    fi
    
    if ! prompt_yes_no "Enable two-factor authentication (Google Authenticator)?" "n"; then
        log_info "2FA setup skipped"
        return 0
    fi
    
    log_info "Setting up two-factor authentication"
    
    # Install Google Authenticator
    install_package "libpam-google-authenticator"
    
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure 2FA"
        return 0
    fi
    
    # Configure PAM
    local pam_sshd="/etc/pam.d/sshd"
    backup_file "$pam_sshd"
    
    if ! grep -q "pam_google_authenticator.so" "$pam_sshd"; then
        sed -i '/@include common-auth/a auth required pam_google_authenticator.so nullok' "$pam_sshd"
        log_info "PAM configuration updated"
    fi
    
    # Update SSH config for 2FA
    sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
    
    if ! grep -q "AuthenticationMethods" /etc/ssh/sshd_config; then
        echo "AuthenticationMethods publickey,keyboard-interactive" >> /etc/ssh/sshd_config
    fi
    
    log_success "2FA base configuration complete"
    log_warning "Each user must run 'google-authenticator' to complete setup"
    
    # Offer to set up for current admin user
    if prompt_yes_no "Set up 2FA for $ADMIN_USERNAME now?" "y"; then
        log_info "Switching to $ADMIN_USERNAME to run google-authenticator"
        su - "$ADMIN_USERNAME" -c "google-authenticator -t -d -f -r 3 -R 30 -w 3"
        log_success "2FA configured for $ADMIN_USERNAME"
    fi
    
    return 0
}
