#!/bin/bash
# ============================================================================
# Linux Base Setup v2.0
# Modular Server Hardening Script
# ============================================================================
# Author: Generated by linux-base-setup
# Description: Automated security hardening for Debian/Ubuntu servers
# Repository: https://github.com/crxnit/linux-base-setup
# ============================================================================

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ============================================================================
# Initialize Configuration
# ============================================================================

# Load default configuration
if [[ -f "$SCRIPT_DIR/config/default.conf" ]]; then
    # shellcheck source=config/default.conf
    source "$SCRIPT_DIR/config/default.conf"
else
    echo "ERROR: Default configuration file not found!"
    exit 1
fi

# Load custom configuration if exists
if [[ -f "$SCRIPT_DIR/config/custom.conf" ]]; then
    # shellcheck source=config/custom.conf
    source "$SCRIPT_DIR/config/custom.conf"
    echo "Loaded custom configuration"
fi

# ============================================================================
# Parse Command Line Arguments
# ============================================================================

print_usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Modular Linux server hardening script for Debian/Ubuntu systems.

OPTIONS:
    -h, --help              Show this help message
    -d, --dry-run           Preview changes without applying them
    -c, --config FILE       Use custom configuration file
    -i, --interactive       Force interactive mode
    -n, --non-interactive   Force non-interactive mode
    -v, --verbose           Enable verbose output
    --skip-updates          Skip system updates
    --skip-ssh              Skip SSH configuration
    --skip-firewall         Skip firewall configuration
    --skip-fail2ban         Skip Fail2Ban installation
    --skip-auditd           Skip Auditd installation
    
EXAMPLES:
    # Preview changes without applying
    sudo $(basename "$0") --dry-run
    
    # Run with custom config
    sudo $(basename "$0") --config /path/to/custom.conf
    
    # Non-interactive mode (use defaults)
    sudo $(basename "$0") --non-interactive
    
    # Skip specific components
    sudo $(basename "$0") --skip-updates --skip-firewall

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            print_usage
            exit 0
            ;;
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -c|--config)
            if [[ -f "$2" ]]; then
                source "$2"
                echo "Loaded configuration from: $2"
            else
                echo "ERROR: Configuration file not found: $2"
                exit 1
            fi
            shift 2
            ;;
        -i|--interactive)
            INTERACTIVE=true
            shift
            ;;
        -n|--non-interactive)
            INTERACTIVE=false
            shift
            ;;
        -v|--verbose)
            set -x
            shift
            ;;
        --skip-updates)
            PERFORM_UPDATES=false
            shift
            ;;
        --skip-ssh)
            CONFIGURE_SSH=false
            shift
            ;;
        --skip-firewall)
            CONFIGURE_FIREWALL=false
            shift
            ;;
        --skip-fail2ban)
            INSTALL_FAIL2BAN=false
            shift
            ;;
        --skip-auditd)
            INSTALL_AUDITD=false
            shift
            ;;
        *)
            echo "ERROR: Unknown option: $1"
            print_usage
            exit 1
            ;;
    esac
done

# ============================================================================
# Initialize Logging
# ============================================================================

# Create log directory
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/hardening-$(date +%Y%m%d_%H%M%S).log"

# Create backup directory
mkdir -p "$BACKUP_DIR"

echo "Log file: $LOG_FILE"
echo "Backup directory: $BACKUP_DIR"

# ============================================================================
# Load Modules
# ============================================================================

MODULES=(
    "utils"
    "user"
    "ssh"
    "firewall"
    "hardening"
    "security_tools"
    "updates"
)

for module in "${MODULES[@]}"; do
    module_path="$SCRIPT_DIR/modules/${module}.sh"
    if [[ -f "$module_path" ]]; then
        # shellcheck source=/dev/null
        source "$module_path"
    else
        echo "ERROR: Module not found: $module_path"
        exit 1
    fi
done

# ============================================================================
# Pre-flight Checks
# ============================================================================

preflight_checks() {
    log_section "Pre-flight Checks"
    
    # Check if running as root
    check_root
    
    # Check distribution
    check_distribution
    
    # Display system information
    log_info "System Information:"
    get_system_info | tee -a "$LOG_FILE"
    
    # Check disk space
    local available_space
    available_space=$(df -BG / | awk 'NR==2 {print $4}' | sed 's/G//')
    if [[ $available_space -lt 2 ]]; then
        log_warning "Low disk space: ${available_space}GB available"
        if [[ "$INTERACTIVE" == "true" ]]; then
            if ! prompt_yes_no "Continue anyway?" "n"; then
                exit 1
            fi
        fi
    fi
    
    log_success "Pre-flight checks passed"
}

# ============================================================================
# Display Configuration Summary
# ============================================================================

display_summary() {
    log_section "Configuration Summary"
    
    echo "System Configuration:" | tee -a "$LOG_FILE"
    echo "  Dry Run: $DRY_RUN" | tee -a "$LOG_FILE"
    echo "  Interactive: $INTERACTIVE" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    
    echo "Components to Configure:" | tee -a "$LOG_FILE"
    echo "  System Updates: $PERFORM_UPDATES" | tee -a "$LOG_FILE"
    echo "  Unattended Upgrades: $ENABLE_UNATTENDED_UPGRADES" | tee -a "$LOG_FILE"
    echo "  Admin User: $CREATE_ADMIN_USER" | tee -a "$LOG_FILE"
    echo "  SSH Hardening: $CONFIGURE_SSH" | tee -a "$LOG_FILE"
    echo "  SSH Port: $SSH_PORT" | tee -a "$LOG_FILE"
    echo "  Firewall ($FIREWALL_TYPE): $CONFIGURE_FIREWALL" | tee -a "$LOG_FILE"
    echo "  Fail2Ban: $INSTALL_FAIL2BAN" | tee -a "$LOG_FILE"
    echo "  Auditd: $INSTALL_AUDITD" | tee -a "$LOG_FILE"
    echo "  Kernel Hardening: $CONFIGURE_SYSCTL" | tee -a "$LOG_FILE"
    echo "  RKHunter: $INSTALL_RKHUNTER" | tee -a "$LOG_FILE"
    echo "  NTP ($NTP_SERVICE): $CONFIGURE_NTP" | tee -a "$LOG_FILE"
    echo "  Hostname: $CONFIGURE_HOSTNAME" | tee -a "$LOG_FILE"
    echo "" | tee -a "$LOG_FILE"
    
    if [[ "$INTERACTIVE" == "true" ]] && [[ "$DRY_RUN" != "true" ]]; then
        if ! prompt_yes_no "Proceed with hardening?" "y"; then
            log_warning "Hardening cancelled by user"
            exit 0
        fi
    fi
}

# ============================================================================
# Main Execution
# ============================================================================

main() {
    # Banner
    cat <<'EOF'
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║           Linux Base Setup v2.0                               ║
║           Modular Server Hardening                            ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
    
    log_info "Starting hardening process at $(date)"
    
    # Pre-flight checks
    preflight_checks
    
    # Display summary
    display_summary
    
    # Set trap for cleanup on error
    trap cleanup_on_error ERR
    
    # Execute hardening steps
    log_section "BEGIN HARDENING PROCESS"
    
    # 1. System updates
    perform_system_updates
    
    # 2. Configure hostname
    configure_hostname
    
    # 3. Create admin user
    create_admin_user
    
    # 4. Setup SSH keys
    if [[ "$CREATE_ADMIN_USER" == "true" ]]; then
        setup_ssh_keys
    fi
    
    # 5. Configure password policy
    configure_password_policy
    
    # 6. Configure umask
    configure_umask
    
    # 7. SSH hardening
    configure_ssh
    
    # 8. Firewall configuration
    configure_firewall
    
    # 9. Kernel hardening
    configure_sysctl_hardening
    disable_uncommon_protocols
    configure_shared_memory
    configure_coredumps
    configure_kernel_modules
    
    # 10. USB storage
    if [[ "$DISABLE_USB_STORAGE" == "true" ]]; then
        disable_usb_storage
    fi
    
    # 11. AppArmor
    if [[ "$CONFIGURE_APPARMOR" == "true" ]]; then
        configure_apparmor
    fi
    
    # 12. Security tools
    configure_fail2ban
    configure_auditd
    install_rkhunter
    install_lynis
    
    # 13. Unattended upgrades
    configure_unattended_upgrades
    
    # 14. NTP and timezone
    configure_ntp
    
    # 15. Optional: 2FA
    if [[ "$CONFIGURE_SSH" == "true" ]]; then
        setup_ssh_two_factor
    fi
    
    # 16. Rate limiting
    if [[ "$CONFIGURE_FIREWALL" == "true" ]]; then
        configure_rate_limiting
    fi
    
    # Completion
    log_section "HARDENING COMPLETE"
    
    generate_completion_report
    
    # Restart SSH if configured
    if [[ "$CONFIGURE_SSH" == "true" ]] && [[ "$DRY_RUN" != "true" ]]; then
        restart_ssh_safe
    fi
    
    log_success "Server hardening completed successfully at $(date)"
    
    return 0
}

# ============================================================================
# Completion Report
# ============================================================================

generate_completion_report() {
    local report_file="${BACKUP_DIR}/completion_report.txt"
    
    cat > "$report_file" <<EOF
============================================
Linux Base Setup - Completion Report
============================================
Date: $(date)
Hostname: $(hostname)
IP Address: $(hostname -I | awk '{print $1}')

CONFIGURATION SUMMARY
============================================
EOF
    
    if [[ "$CREATE_ADMIN_USER" == "true" ]] && [[ -n "$ADMIN_USERNAME" ]]; then
        cat >> "$report_file" <<EOF

Admin User: $ADMIN_USERNAME
  - SSH Key: $([ -f "/home/$ADMIN_USERNAME/.ssh/authorized_keys" ] && echo "Configured" || echo "Not configured")
  - Groups: $(groups "$ADMIN_USERNAME" 2>/dev/null | cut -d: -f2 || echo "N/A")
EOF
    fi
    
    if [[ "$CONFIGURE_SSH" == "true" ]]; then
        cat >> "$report_file" <<EOF

SSH Configuration:
  - Port: $SSH_PORT
  - Root Login: $SSH_PERMIT_ROOT_LOGIN
  - Password Auth: $SSH_PASSWORD_AUTH
  - Pubkey Auth: $SSH_PUBKEY_AUTH
  
  Connection Command:
    ssh -p $SSH_PORT $ADMIN_USERNAME@$(hostname -I | awk '{print $1}')
EOF
    fi
    
    if [[ "$CONFIGURE_FIREWALL" == "true" ]]; then
        cat >> "$report_file" <<EOF

Firewall ($FIREWALL_TYPE):
  - Status: $(systemctl is-active ufw 2>/dev/null || systemctl is-active firewalld 2>/dev/null || echo "unknown")
  - SSH Port: $SSH_PORT/tcp allowed
EOF
    fi
    
    cat >> "$report_file" <<EOF

CRITICAL NEXT STEPS
============================================
1. TEST SSH CONNECTION from another terminal:
   ssh -p $SSH_PORT $ADMIN_USERNAME@$(hostname -I | awk '{print $1}')

2. Verify firewall rules allow required services

3. Review log file: $LOG_FILE

4. Review backup directory: $BACKUP_DIR

5. Consider running security audit:
   sudo lynis audit system

IMPORTANT FILES
============================================
- Log File: $LOG_FILE
- Backup Directory: $BACKUP_DIR
- Configuration: $SCRIPT_DIR/config/

For support or issues, visit:
https://github.com/crxnit/linux-base-setup

============================================
EOF
    
    # Display report
    cat "$report_file" | tee -a "$LOG_FILE"
    
    log_info "Full report saved to: $report_file"
}

# ============================================================================
# Execute Main Function
# ============================================================================

main "$@"
