#!/bin/bash
# ============================================================================
# Cloud-Init Configuration Generator
# ============================================================================
# Generates a cloud-init.yaml from the Linux Base Setup configuration.
# Includes first-boot hardening that runs before SSH is accessible.
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Default output file
OUTPUT_FILE=""
CONFIG_FILE=""
SSH_PUBKEY=""
SSH_PUBKEY_FILE=""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Generate a cloud-init.yaml file from Linux Base Setup configuration.

Options:
  -c, --config FILE       Path to configuration file (default: config/default.conf)
  -o, --output FILE       Output file path (default: stdout)
  -k, --ssh-key KEY       SSH public key string
  -f, --ssh-key-file FILE Path to SSH public key file (e.g., ~/.ssh/id_ed25519.pub)
  -u, --username NAME     Admin username (overrides config)
  -t, --timezone TZ       Timezone (e.g., America/New_York)
  -h, --help              Show this help message

Examples:
  # Generate to stdout with SSH key from file
  $(basename "$0") -f ~/.ssh/id_ed25519.pub

  # Generate with custom config and output file
  $(basename "$0") -c config/custom.conf -o my-cloud-init.yaml -f ~/.ssh/id_rsa.pub

  # Generate with inline SSH key and custom username
  $(basename "$0") -k "ssh-ed25519 AAAA... user@host" -u myadmin

EOF
    exit 0
}

log_info() { echo -e "${BLUE}[INFO]${NC} $1" >&2; }
log_success() { echo -e "${GREEN}[OK]${NC} $1" >&2; }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -c|--config)
            CONFIG_FILE="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -k|--ssh-key)
            SSH_PUBKEY="$2"
            shift 2
            ;;
        -f|--ssh-key-file)
            SSH_PUBKEY_FILE="$2"
            shift 2
            ;;
        -u|--username)
            ADMIN_USERNAME="$2"
            shift 2
            ;;
        -t|--timezone)
            TIMEZONE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Find and load configuration
if [[ -n "$CONFIG_FILE" ]]; then
    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_error "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi
else
    # Try to find default config
    for path in "$PROJECT_ROOT/config/default.conf" "/opt/linux-base-setup/config/default.conf" "/etc/linux-base-setup/default.conf"; do
        if [[ -f "$path" ]]; then
            CONFIG_FILE="$path"
            break
        fi
    done
fi

if [[ -z "$CONFIG_FILE" ]]; then
    log_error "No configuration file found. Use -c to specify one."
    exit 1
fi

log_info "Loading configuration from: $CONFIG_FILE"
# shellcheck source=/dev/null
source "$CONFIG_FILE"

# Load SSH key from file if specified
if [[ -n "$SSH_PUBKEY_FILE" ]]; then
    if [[ ! -f "$SSH_PUBKEY_FILE" ]]; then
        log_error "SSH key file not found: $SSH_PUBKEY_FILE"
        exit 1
    fi
    SSH_PUBKEY=$(cat "$SSH_PUBKEY_FILE")
    log_info "Loaded SSH key from: $SSH_PUBKEY_FILE"
fi

# Validate required settings
if [[ -z "$SSH_PUBKEY" ]]; then
    log_error "SSH public key is required. Use -k or -f option."
    exit 1
fi

if [[ -z "$ADMIN_USERNAME" ]]; then
    log_error "Admin username is required. Set in config or use -u option."
    exit 1
fi

# Set defaults for optional settings
TIMEZONE="${TIMEZONE:-UTC}"
HOSTNAME_PREFIX="${HOSTNAME_PREFIX:-srv}"
SSH_PORT="${SSH_PORT:-22}"
ADMIN_USER_SHELL="${ADMIN_USER_SHELL:-/bin/bash}"
DEFAULT_UMASK="${DEFAULT_UMASK:-027}"
NTP_SERVICE="${NTP_SERVICE:-chrony}"

# Generate sysctl values based on config
get_sysctl_value() {
    local var_name="$1"
    local default="$2"
    local value="${!var_name:-$default}"
    if [[ "$value" == "true" ]]; then
        echo "1"
    else
        echo "0"
    fi
}

# Build the cloud-init YAML
generate_cloud_init() {
    cat <<EOF
#cloud-config
# ============================================================================
# Linux Base Setup - Cloud-Init Configuration
# ============================================================================
# Generated by generate-cloud-init.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source config: $CONFIG_FILE
#
# This cloud-init handles first-boot hardening before SSH is accessible.
# For advanced features (2FA, CrowdSec, etc.), run harden.sh after boot.
# ============================================================================

# --- Hostname Configuration ---
# Auto-generates hostname with prefix if not set by cloud provider
hostname: ${HOSTNAME_PREFIX}-\${INSTANCE_ID}
manage_etc_hosts: true
prefer_fqdn_over_hostname: false

# --- Timezone ---
timezone: $TIMEZONE

# --- User Configuration ---
users:
  - name: $ADMIN_USERNAME
    groups: [sudo, adm]
    shell: $ADMIN_USER_SHELL
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - $SSH_PUBKEY

# Disable root SSH login
disable_root: true

# --- Package Management ---
package_update: true
package_upgrade: true

packages:
  # Essential tools
  - curl
  - wget
  - git
  - vim
  - gnupg
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  # SSH
  - openssh-server
  # NTP
EOF

    # Add NTP package based on config
    if [[ "$NTP_SERVICE" == "chrony" ]]; then
        echo "  - chrony"
    else
        echo "  - systemd-timesyncd"
    fi

    cat <<EOF

# --- Write Configuration Files ---
write_files:
  # Kernel hardening (sysctl)
  - path: /etc/sysctl.d/99-hardening.conf
    owner: root:root
    permissions: '0644'
    content: |
      # Kernel Hardening Configuration
      # Generated by linux-base-setup cloud-init

      # IP Forwarding
      net.ipv4.ip_forward = $(get_sysctl_value SYSCTL_IP_FORWARDING false)
      net.ipv6.conf.all.forwarding = $(get_sysctl_value SYSCTL_IP_FORWARDING false)

      # Source routing (disable)
      net.ipv4.conf.all.accept_source_route = $(get_sysctl_value SYSCTL_ACCEPT_SOURCE_ROUTE false)
      net.ipv4.conf.default.accept_source_route = $(get_sysctl_value SYSCTL_ACCEPT_SOURCE_ROUTE false)
      net.ipv6.conf.all.accept_source_route = $(get_sysctl_value SYSCTL_ACCEPT_SOURCE_ROUTE false)
      net.ipv6.conf.default.accept_source_route = $(get_sysctl_value SYSCTL_ACCEPT_SOURCE_ROUTE false)

      # ICMP redirects (disable)
      net.ipv4.conf.all.accept_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)
      net.ipv4.conf.default.accept_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)
      net.ipv6.conf.all.accept_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)
      net.ipv6.conf.default.accept_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)
      net.ipv4.conf.all.secure_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)
      net.ipv4.conf.default.secure_redirects = $(get_sysctl_value SYSCTL_ACCEPT_REDIRECTS false)

      # Send redirects (disable)
      net.ipv4.conf.all.send_redirects = $(get_sysctl_value SYSCTL_SEND_REDIRECTS false)
      net.ipv4.conf.default.send_redirects = $(get_sysctl_value SYSCTL_SEND_REDIRECTS false)

      # Reverse path filtering (anti-spoofing)
      net.ipv4.conf.all.rp_filter = $(get_sysctl_value SYSCTL_RP_FILTER true)
      net.ipv4.conf.default.rp_filter = $(get_sysctl_value SYSCTL_RP_FILTER true)

      # Log Martians (packets with impossible addresses)
      net.ipv4.conf.all.log_martians = $(get_sysctl_value SYSCTL_LOG_MARTIANS true)
      net.ipv4.conf.default.log_martians = $(get_sysctl_value SYSCTL_LOG_MARTIANS true)

      # SYN flood protection
      net.ipv4.tcp_syncookies = $(get_sysctl_value SYSCTL_TCP_SYNCOOKIES true)
      net.ipv4.tcp_max_syn_backlog = 2048
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_syn_retries = 5

      # ICMP broadcast/multicast
      net.ipv4.icmp_echo_ignore_broadcasts = $(get_sysctl_value SYSCTL_ICMP_ECHO_IGNORE_BROADCASTS true)
      net.ipv4.icmp_ignore_bogus_error_responses = $(get_sysctl_value SYSCTL_ICMP_IGNORE_BOGUS_ERROR_RESPONSES true)

      # Kernel hardening
      kernel.dmesg_restrict = $(get_sysctl_value SYSCTL_KERNEL_DMESG_RESTRICT true)
      kernel.kptr_restrict = $(get_sysctl_value SYSCTL_KERNEL_KPTR_RESTRICT true)
      kernel.randomize_va_space = $([ "${SYSCTL_RANDOMIZE_VA_SPACE:-true}" == "true" ] && echo "2" || echo "0")
      kernel.yama.ptrace_scope = 1
      kernel.panic = 10
      kernel.panic_on_oops = 1

      # Core dump restrictions
      fs.suid_dumpable = 0

      # Network performance tuning
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      net.core.rmem_default = 67108864
      net.core.wmem_default = 67108864
      net.core.netdev_max_backlog = 5000
      net.core.somaxconn = 4096

      # IPv6 hardening
      net.ipv6.conf.all.disable_ipv6 = 0
      net.ipv6.conf.default.disable_ipv6 = 0
      net.ipv6.conf.lo.disable_ipv6 = 0
      net.ipv6.conf.all.accept_ra = 0
      net.ipv6.conf.default.accept_ra = 0

      # Filesystem protections
      fs.protected_hardlinks = 1
      fs.protected_symlinks = 1
      fs.protected_fifos = 2
      fs.protected_regular = 2

  # SSH daemon configuration (hardened)
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    owner: root:root
    permissions: '0600'
    content: |
      # SSH Hardening Configuration
      # Generated by linux-base-setup cloud-init

      # Network
      Port $SSH_PORT
      AddressFamily inet

      # Protocol
      Protocol 2

      # Ciphers and keying (modern, secure)
      KexAlgorithms ${SSH_KEY_EXCHANGE_ALGORITHMS:-curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256}
      Ciphers ${SSH_CIPHERS:-chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr}
      MACs ${SSH_MACS:-hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256}
      HostKeyAlgorithms ${SSH_HOST_KEY_ALGORITHMS:-ssh-ed25519,rsa-sha2-512,rsa-sha2-256}

      # Logging
      SyslogFacility AUTH
      LogLevel VERBOSE

      # Authentication
      LoginGraceTime ${SSH_LOGIN_GRACE_TIME:-30}s
      PermitRootLogin ${SSH_PERMIT_ROOT_LOGIN:-no}
      StrictModes yes
      MaxAuthTries ${SSH_MAX_AUTH_TRIES:-3}
      MaxSessions 10

      PubkeyAuthentication ${SSH_PUBKEY_AUTH:-yes}
      PasswordAuthentication ${SSH_PASSWORD_AUTH:-no}
      PermitEmptyPasswords ${SSH_PERMIT_EMPTY_PASSWORDS:-no}
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no

      # Kerberos/GSSAPI
      KerberosAuthentication no
      GSSAPIAuthentication no

      # PAM
      UsePAM ${SSH_USE_PAM:-yes}

      # Forwarding
      AllowAgentForwarding yes
      AllowTcpForwarding yes
      X11Forwarding ${SSH_X11_FORWARDING:-no}

      # Client alive (prevent timeout)
      ClientAliveInterval ${SSH_CLIENT_ALIVE_INTERVAL:-300}
      ClientAliveCountMax ${SSH_CLIENT_ALIVE_COUNT_MAX:-2}

      # Other
      PrintMotd no
      PrintLastLog ${SSH_PRINT_LAST_LOG:-yes}
      TCPKeepAlive yes
      AcceptEnv LANG LC_*

  # SSH banner
  - path: /etc/ssh/banner
    owner: root:root
    permissions: '0644'
    content: |
      ###############################################################################
      #                                                                             #
      #                    AUTHORIZED ACCESS ONLY                                   #
      #                                                                             #
      #  This system is for authorized use only. All activity is monitored and     #
      #  logged. Unauthorized access or use may result in disciplinary action      #
      #  and/or civil and criminal penalties.                                      #
      #                                                                             #
      ###############################################################################

  # Disable uncommon network protocols
  - path: /etc/modprobe.d/uncommon-protocols.conf
    owner: root:root
    permissions: '0644'
    content: |
      # Disable uncommon network protocols
      install dccp /bin/true
      install sctp /bin/true
      install rds /bin/true
      install tipc /bin/true

  # Disable uncommon filesystems
  - path: /etc/modprobe.d/uncommon-filesystems.conf
    owner: root:root
    permissions: '0644'
    content: |
      # Disable uncommon filesystems
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install udf /bin/true

  # Core dump restrictions
  - path: /etc/security/limits.d/10-coredump.conf
    owner: root:root
    permissions: '0644'
    content: |
      # Disable core dumps
      * hard core 0
      * soft core 0

  # Umask configuration
  - path: /etc/profile.d/umask.sh
    owner: root:root
    permissions: '0644'
    content: |
      # Set default umask
      umask $DEFAULT_UMASK

  # Post-install marker for harden.sh
  - path: /etc/linux-base-setup/cloud-init-completed
    owner: root:root
    permissions: '0644'
    content: |
      # Cloud-init hardening completed
      # Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
      # Config: $CONFIG_FILE
      #
      # The following was configured by cloud-init:
      # - Admin user: $ADMIN_USERNAME
      # - SSH hardening (port $SSH_PORT, key-only auth)
      # - Sysctl kernel hardening
      # - Disabled uncommon protocols/filesystems
      # - Core dump restrictions
      # - Umask ($DEFAULT_UMASK)
      # - NTP ($NTP_SERVICE)
      #
      # To complete hardening, run:
      #   sudo harden --skip-users --skip-ssh-basic
      #
      # This will install:
      # - CrowdSec IPS
      # - Auditd
      # - RKHunter
      # - SSH 2FA (optional)
      # - Firewall rules
      # - Unattended upgrades

# --- Run Commands ---
runcmd:
  # Apply sysctl settings
  - sysctl --system

  # Generate Ed25519 SSH host key if missing
  - |
    if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
      ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
    fi

  # Enable SSH banner
  - |
    if ! grep -q "^Banner" /etc/ssh/sshd_config; then
      echo "Banner /etc/ssh/banner" >> /etc/ssh/sshd_config
    fi

  # Restart SSH to apply new configuration
  - systemctl restart sshd

  # Enable and start NTP service
EOF

    if [[ "$NTP_SERVICE" == "chrony" ]]; then
        cat <<EOF
  - systemctl enable chrony
  - systemctl start chrony
EOF
    else
        cat <<EOF
  - systemctl enable systemd-timesyncd
  - systemctl start systemd-timesyncd
EOF
    fi

    cat <<EOF

  # Create directory for linux-base-setup
  - mkdir -p /etc/linux-base-setup

  # Log completion
  - echo "Cloud-init hardening completed at \$(date)" >> /var/log/cloud-init-hardening.log

# --- Final Message ---
final_message: |
  ===========================================
  Linux Base Setup - Cloud-Init Complete
  ===========================================
  System hardened and ready.

  SSH Access:
    ssh -p $SSH_PORT $ADMIN_USERNAME@\$PUBLIC_IP

  To complete hardening (CrowdSec, 2FA, etc.):
    curl -sSL https://raw.githubusercontent.com/crxnit/Linux-Base-Setup-2026/main/install.sh | sudo bash
    sudo harden

  Cloud-init completed in \$UPTIME seconds.
  ===========================================
EOF
}

# Generate and output
if [[ -n "$OUTPUT_FILE" ]]; then
    generate_cloud_init > "$OUTPUT_FILE"
    log_success "Cloud-init configuration written to: $OUTPUT_FILE"
    log_info "Use with: cloud-init validate $OUTPUT_FILE"
else
    generate_cloud_init
fi
